version: '3.8'

services:
  # MySQL Database Service
  db:
    image: mysql:5.7
    volumes:
      - ./db_data:/db_data
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: englishwithellen
      MYSQL_USER: ellen
      MYSQL_PASSWORD: secret
    networks:
      - wordpress_network

  # WordPress Service
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - .:/var/www/html  # Map to a local directory
    ports:
      - "3000:80"
    restart: always
    environment:
      # debug mode
      # WORDPRESS_DEBUG: 1

      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ellen
      WORDPRESS_DB_PASSWORD: secret
      WORDPRESS_DB_NAME: englishwithellen
    networks:
      - wordpress_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - "3081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - wordpress_network

# Define volumes and networks
volumes:
  db_data:
  wp_data:

networks:
  wordpress_network:
